---

- hosts: all
  become: true
  tasks:

  - name: install the apache2 package
    package: 
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes 
