---

- hosts: all
  become: true
  tasks:

  - name: install the apache2 package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes 
    when: ansible_distribution == "Ubuntu"

  - name: install the apache2 package
    dnf: 
      name: 
        - httpd
        - php 
      state: latest
      update_cache: yes 
    when: ansible_distribution == "CentOS"

